name: schedule

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  init:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install cgiproxy
